name: Deploy to Droplet

on:
  push:
    branches: [main]  # or master, whatever your main branch is

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

    - name: Run deploy script on droplet
      run: ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} 'bash /var/www/oneshotauto/oneshotauto/scripts/deploy.sh'